name: Build RootX ESP-IDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.5 # Pake container resmi biar gak butuh action luar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build Firmware
        run: |
          # 1. Aktifkan environment IDF (Kunci biar idf.py ketemu)
          . $IDF_PATH/export.sh
          
          # 2. Paksa pake sdkconfig sakti lu
          cp sdkconfig.defaults sdkconfig
          
          # 3. Set target ke S3
          idf.py set-target esp32s3
          
          # 4. Build sampai jadi .bin
          idf.py build


      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RootX-S3-Firmware
          path: build/*.bin
          
