name: Build RootX ESP-IDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.5 # Pake container resmi biar gak butuh action luar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build Firmware
        run: |
          . $IDF_PATH/export.sh
          
          # --- PROSES JEBOL FIREWALL (BINARY PATCH) ---
          # Kita cari instruksi yang nge-block 0xC0 di library WiFi S3
          # Dan kita paksa jadi 'selalu diizinkan'
          find /opt/esp/idf/components/esp_wifi/lib/esp32s3/ -name "libnet80211.a" -exec chmod +w {} \;
          find /opt/esp/idf/components/esp_wifi/lib/esp32s3/ -name "libnet80211.a" -exec sed -i 's/\x0c\x00\x00\x00\xeb/\x0c\x00\x00\x00\xe9/g' {} \;
          
          # Paksa pake sdkconfig sakti
          cp sdkconfig.defaults sdkconfig
          idf.py set-target esp32s3
          idf.py build



      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RootX-S3-Firmware
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/*.bin
            build/flashing_args

